image: gitpod/workspace-full

# Commands that will run on workspace start
tasks:
  - name: Setup & Build
    before: |
      sudo apt update
      sudo apt install -y software-properties-common
      sudo add-apt-repository -y ppa:ondrej/php
      sudo apt update
      sudo apt install -y php8.3 php8.3-sqlite3
      touch database/database.sqlite
      sudo mkdir -p --mode=0755 /usr/share/keyrings
      curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
      echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflared.list
      sudo apt-get update && sudo apt-get install cloudflared
      cloudflared tunnel login
